# Generated by Django 5.0.4 on 2024-04-27 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_orders_customer_remove_orders_product_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 27, 18, 43, 38, 411588)),
        ),
    ]
