# Generated by Django 5.0.4 on 2024-04-28 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_new_price_product_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 28, 20, 58, 29, 260139)),
        ),
    ]
