# Generated by Django 5.0.4 on 2024-04-29 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_model_image_1_product_model_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 29, 18, 55, 7, 95074)),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_image_1',
            field=models.ImageField(upload_to='', verbose_name='uploads/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_image_2',
            field=models.ImageField(upload_to='', verbose_name='uploads/products'),
        ),
    ]
