# Generated by Django 5.0.4 on 2024-04-29 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_image',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 29, 18, 58, 15, 761528)),
        ),
    ]
