# Generated by Django 5.0.4 on 2024-04-29 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_model_image_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mimage_1',
            field=models.ImageField(null=True, upload_to='', verbose_name='uploads/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='mimage_2',
            field=models.ImageField(null=True, upload_to='', verbose_name='uploads/products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 29, 18, 59, 25, 452704)),
        ),
    ]
