# Generated by Django 5.0.4 on 2024-04-29 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_order_date_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mimage_1',
            new_name='model_image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mimage_2',
            new_name='model_image_2',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 29, 19, 5, 27, 969152)),
        ),
    ]
