# Generated by Django 5.0.4 on 2024-04-29 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_order_date_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 4, 29, 19, 8, 31, 164629)),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_image_1',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='uploads/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_image_2',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='uploads/products'),
        ),
    ]
