# Generated by Django 5.0.4 on 2024-05-01 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_order_date_alter_product_model_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 1, 22, 28, 4, 280794)),
        ),
    ]
