# Generated by Django 5.0.2 on 2024-05-16 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 16, 23, 54, 50, 439877)),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
