# Generated by Django 5.0.2 on 2024-05-19 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_order_order_date_alter_productsize_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 19, 23, 38, 27, 719262)),
        ),
    ]
