# Generated by Django 5.0.4 on 2024-05-29 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_order_order_date_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 29, 21, 34, 28, 574143)),
        ),
    ]
