# Generated by Django 5.0.4 on 2024-05-29 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 5, 29, 21, 44, 42, 12315)),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
