# Generated by Django 5.0.4 on 2024-07-28 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_category_image_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 28, 11, 27, 42, 603199)),
        ),
    ]
