# Generated by Django 5.0.2 on 2024-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='per_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
