# Generated by Django 5.0.2 on 2024-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_shippingaddress_per_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='add_information',
            field=models.TextField(null=True),
        ),
    ]
