# Generated by Django 5.0.2 on 2024-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
