# Generated by Django 5.0.2 on 2024-05-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_my_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_orders',
        ),
    ]
