# Generated by Django 5.0.4 on 2024-07-28 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_delete_my_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creted', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('code', models.CharField(max_length=7)),
                ('sale_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='per_id',
            new_name='payment_methode',
        ),
        migrations.AddField(
            model_name='order',
            name='cupon_used',
            field=models.CharField(default='Cupon code was not used', max_length=200, null=True),
        ),
    ]
