# Generated by Django 5.0.4 on 2024-04-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_profile_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
